// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdn_fosJUmDWxFHMXzK2ZxbAV63MUNYek',
    appId: '1:584161744453:web:464e5033628a45b40cf52c',
    messagingSenderId: '584161744453',
    projectId: 'ubademy-2dc37',
    authDomain: 'ubademy-2dc37.firebaseapp.com',
    storageBucket: 'ubademy-2dc37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUN00aSbLbZdsKcxjxqvLwUWLoVGinDNM',
    appId: '1:584161744453:android:4620eeff0492b39d0cf52c',
    messagingSenderId: '584161744453',
    projectId: 'ubademy-2dc37',
    storageBucket: 'ubademy-2dc37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDv0f4L2KDM2R4JwW9oZtcZ9eOPmcs3PU',
    appId: '1:584161744453:ios:a119b49c8c80fbad0cf52c',
    messagingSenderId: '584161744453',
    projectId: 'ubademy-2dc37',
    storageBucket: 'ubademy-2dc37.appspot.com',
    androidClientId:
        '584161744453-fgaj91g8300kchrgf7nqavdgq5j0fh0p.apps.googleusercontent.com',
    iosClientId:
        '584161744453-i6rehfgkifs83eio158jqkrrlhr86jcb.apps.googleusercontent.com',
    iosBundleId: 'com.fiuba.fiubademy',
  );
}
